version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.2
    steps:
      - checkout
      - run: cd tests/TodosTests
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build